samples: config/samples.tsv

units: config/units.tsv

# Optional BED file with target regions
# target_regions: "path/to/taget-regions.bed"

ref:
  # Number of chromosomes to consider for calling.
  # The first n entries of the FASTA will be considered.
  n_chromosomes: 25
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release
  release: 106
  # Genome build
  build: GRCh38
  # Optionally, instead of downloading the whole reference from Ensembl via the 
  # parameters above, specify a specific chromosome below and uncomment the line.
  # This is usually only relevant for testing.
  # chromosome: 21

primers:
  trimming:
    activate: true
    # path to fasta files containg primer sequences
    primers_fa1: "config/panel_primer.1.fa"
    primers_fa2: "config/panel_primer.2.fa"
    # optional primer file allowing to define primers per sample
    # overwrites primers_fa1 and primers_fa2
    # the tsv file requires three fields: panel, fa1 and fa2 (optional)
    tsv: ""
    # Mean insert size between the outer primer ends.
    # If 0 or not set the bowtie default value of 250 will be used
    library_length: 0

# Estimation of tumor mutational burden.
mutational_burden:
  activate: false
  # Plotting modes - hist (stratified histogram)
  # or curve (stratified curve)
  mode:
    - curve
    - hist

# printing of variants in interactive tables
report:
  # if stratification is deactivated, one report for all
  # samples will be created.
  activate: true
  max_read_depth: 250
  stratify:
    activate: false
    # select a sample sheet column for stratification
    by-column: condition

calling:
  # Set to true to infer classical genotypes from Varlociraptor's VAF predictions
  infer_genotypes: false
  delly:
    activate: true
  freebayes:
    activate: true
  # See https://varlociraptor.github.io/docs/calling/#generic-variant-calling
  scenario: config/scenario.yaml
  filter:
    # Filter candidate variants (this filter helps to keep the number of evaluated candidates small).
    # It should ideally generate a superset of all other filters defined below.
    # Annotation of candidate variants tries to be as fast as possible, only using VEP
    # default parameters. Comment out or remove if not needed or intended.
    # See https://github.com/vembrane/vembrane
    # candidates: "ANN['IMPACT'] != 'LOW'"
    # Add any number of named filters here (replace myfilter with a reasonable name, 
    # and add more below). Filtering happens with the vembrane filter language
    # (see https://github.com/vembrane/vembrane), and you can refer to any fields that
    # have been added by VEP during annotation (in the INFO/ANN field, see section 
    # annotations/vep below).
    # Filters will be applied independenty, and can be referred in FDR control below
    # to generate calls for different events.
    # You can for example filter by ANN fields, ID or dbsnp annotations here.
    moderate_high: "any(entry in ANN['IMPACT'] for entry in ('HIGH','MODERATE'))"
    # If you need to use vembrane command line options beyond the filter expression,
    # please use the filter sub-structure with 'expression:' for the filter expression
    # and "aux-files:" for additional files with IDs for filtering. This can for example 
    # be used for filtering by gene lists (with a file containing one gene name per line).
    gene_list_filter:
      aux-files:
        super_interesting_genes: "config/super_interesting_genes.tsv"
      expression: "ANN['SYMBOL'] in AUX['super_interesting_genes']"
  fdr-control:
    threshold: 0.01
    # denote whether local or global FDR shall be controlled
    local: true
    events: 
      # Add any number of events here to filter for.
      # The id of each event can be chosen freely, but needs to contain
      # only alphanumerics and underscores
      # ("somatic" below is just an example and can be modified as needed).
      ctDNA:
        # labels for the callset, displayed in the report. Will fall back to id if no labels specified
        labels:
          events: ctDNA
        # optional subcategory for callset (e.g. "known variants", or "VUS"),
        # comment out or remove to disable
        # subcategory: some subcategory
        # Natural language description of the callset obtained here.
        # This will occur in the report.
        desc: |
          Analysis of cell-free circulating tumor DNA (ctDNA). 
        varlociraptor: 
          # Add varlociraptor events to aggregated over.
          # The probability for the union of these events is used for controlling
          # the FDR.
          - "HIGH"
        filter: # myfilter
          # Add any number of filters here.
          # A single filter can be set as string.
          # Multiple filters can be defined as list and will be concatenated by 'and'
          - moderate_high
          - gene_list_filter

# If calc_consensus_reads is activated duplicates will be merged
remove_duplicates:
  activate: false

# Experimental: calculate consensus reads from PCR duplicates.
# if 'remove_duplicates' is deactivate only overlapping pairs will be merged
calc_consensus_reads:
  activate: false

annotations:
  vcfs:
    activate: true
    # annotate with known variants from ensembl
    known: resources/variation.vcf.gz
    # add more external VCFs as needed
    cosmic: resources/CosmicCodingMuts_hg38_v94.vcf.gz
    clin_var: resources/clinvar_20220425.vcf.gz
  dgidb:
    # annotate variants with drug interactions of affected genes
    activate: false
    # List of datasources for filtering dgidb entries
    # Available sources can be found on http://dgidb.org/api/v2/interaction_sources.json
    datasources:
      - DrugBank
  vep:
    # Consider removing --everything if VEP is slow for you (e.g. for WGS), 
    # and think carefully about which annotations you need.
    params: --everything --check_existing
    plugins:
      # Add any plugin from https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html
      # Plugin args can be passed as well, e.g. "LoFtool,path/to/custom/scores.txt".
      - LoFtool
      - REVEL

# printing of variants in a table format (might be deprecated soon)
tables:
  activate: true
  output:
    # Uncomment and add VEP annotation fields to include (IMPACT, Consequence, Feature, SYMBOL, and HGVSp are always included)
    annotation_fields:
      - EXON
      - CLIN_SIG
    event_prob: true
    observations: true
  generate_excel: false

params:
  cutadapt: ""
  picard:
    MarkDuplicates: "--VALIDATION_STRINGENCY LENIENT"
  gatk:
    BaseRecalibrator: ""
    applyBQSR: ""
  varlociraptor:
    # add extra arguments for varlociraptor call
    # For example, in case of panel data consider to omit certain bias estimations
    # which might be misleading because all reads of an amplicon have the same start
    # position, strand etc. (--omit-strand-bias, --omit-read-position-bias, 
    # --omit-softclip-bias, --omit-read-orientation-bias).
    call: "--omit-strand-bias --omit-read-position-bias --omit-softclip-bias --omit-read-orientation-bias"
    # Add extra arguments for varlociraptor preprocess. By default, we limit the depth to 200.
    # Increase this value for panel sequencing!
    preprocess: "--max-depth 100000"
  freebayes:
    min_alternate_fraction: 0.005 # Reduce for calling variants with lower VAFs
  delly: "-q 20 -s 15 -z 5"
